#!/usr/bin/env bash
set -euo pipefail

# ===== threads / batching =====
THREADS="${SLURM_CPUS_PER_TASK:-10}"
PER_TASK=14

# ===== inputs =====
PROBES=""              # if empty/absent => genome-wide pipeline
SAMPLES_TSV="samples.tsv"
REF="../genotyping_nf_test/reference/subgenome_blue.fasta"
CHROM_SIZE="chrom_size.txt"

# ===== outputs =====
OUTDIR="./out"
TRIM_DIR="${OUTDIR}/trimmomatic"
BAM_TMP_DIR="${OUTDIR}/bam_tmp"
BAM_FINAL_DIR="${OUTDIR}/bam"
PILEUP_DIR="${OUTDIR}/pileup"
SPLIT_DIR="${PILEUP_DIR}/split_chr"
MERGE_DIR="${OUTDIR}/merge"
REPORT_DIR="reports"

# Previous pileups (merge)
USE_PREV_PILEUPS=false
PILEUP_TSV="old_pileup.list"

# ===== chrom list (fixed for species) =====
# ----- Modify this based on the chromosome names used in your genome file ----- 
CHR_LIST=(
  "VaccDscaff1"
  "VaccDscaff2"
  "VaccDscaff4"
  "VaccDscaff6"
  "VaccDscaff7"
  "VaccDscaff11"
  "VaccDscaff12"
  "VaccDscaff13"
  "VaccDscaff17"
  "VaccDscaff20"
  "VaccDscaff21"
  "VaccDscaff22"
)


